// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJhFYmnV_1foqBuGUXoP5htM9-UNhpdTg',
    appId: '1:893584206436:web:6d5a9385cdcfa618bf4d71',
    messagingSenderId: '893584206436',
    projectId: 'penforge-b1e4f',
    authDomain: 'penforge-b1e4f.firebaseapp.com',
    storageBucket: 'penforge-b1e4f.firebasestorage.app',
    measurementId: 'G-QSJ18MTW5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0vKEADqePLgtNEskRd16lZ6wKFeEr7DY',
    appId: '1:893584206436:android:dc94a88c2636723abf4d71',
    messagingSenderId: '893584206436',
    projectId: 'penforge-b1e4f',
    storageBucket: 'penforge-b1e4f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4yLIzor6meYGhHVsg7OENPRFQ61kqnQA',
    appId: '1:893584206436:ios:c5156c161b16a50cbf4d71',
    messagingSenderId: '893584206436',
    projectId: 'penforge-b1e4f',
    storageBucket: 'penforge-b1e4f.firebasestorage.app',
    iosBundleId: 'com.example.penforge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4yLIzor6meYGhHVsg7OENPRFQ61kqnQA',
    appId: '1:893584206436:ios:c5156c161b16a50cbf4d71',
    messagingSenderId: '893584206436',
    projectId: 'penforge-b1e4f',
    storageBucket: 'penforge-b1e4f.firebasestorage.app',
    iosBundleId: 'com.example.penforge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJhFYmnV_1foqBuGUXoP5htM9-UNhpdTg',
    appId: '1:893584206436:web:cf0182736fed44f1bf4d71',
    messagingSenderId: '893584206436',
    projectId: 'penforge-b1e4f',
    authDomain: 'penforge-b1e4f.firebaseapp.com',
    storageBucket: 'penforge-b1e4f.firebasestorage.app',
    measurementId: 'G-L9NNHXPMY3',
  );
}
